[package]
name = "sqlx-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
